# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Postman API Documentation
site_url: https://github.com/voiid16/Postman-API-Documentation

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Sending a GET Request: Task1.md
  - Using Environment Variables : Task2.md
  - Task 3: Task3.md
  - Task 4: Task4.md
  - Troubleshooting: TroubleShooting.md
  - Glossary: glossary.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.keys

docs_dir: docs
