# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Test Docs - Ivy
site_url: https://voiid16.github.io/mkdocs-test/

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Lora
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - mermaid

nav:
  - Home: index.md
  - Task 1: Task1.md
  - Task 2: Task2.md
  - Task 3: Task3.md
  - Task 4: Task4.md
  - Troubleshooting: troubleshooting.md

  # - Getting Started:
  #     - Intro: getting-started/intro.md
  #     - MkDocs vs Material for MkDocs: getting-started/mkdocs-vs-material.md
  #     - Prerequisites: getting-started/prerequisites.md
  #     - Demo Prerequisites: getting-started/demo-prerequisites.md
  #     - Initial Installation: getting-started/installation.md

  # - Configuration:
  #     - Schema Validation: configuration/schema-validation.md
  #     - Color Scheme: configuration/color-scheme.md
  #     - Font: configuration/font.md
  #     - Emojis: configuration/emojis.md
  #     - Icons and Logos: configuration/icons-logos.md
  #     - Footer: configuration/footer.md

  # - Features:
  #     - Code Blocks: features/code-blocks.md
  #     - Content Tabs: features/content-tabs.md
  #     - Admonitions: features/admonitions.md
  #     - Diagrams: features/diagrams.md

  # - Publishing:
  #     - Publishing Your Site: publishing/publishing.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
